[test] Use correct TAP ID for lc_ctrl in e2e_bootstrap_rma
Prior to this change, the test warned that it found a TAP with an
unexpected ID.

    Info : Hardware thread awareness created
    Info : clock speed 200 kHz
    Info : JTAG tap: lc_ctrl.tap tap/device found: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
    Warn : JTAG tap: lc_ctrl.tap       UNEXPECTED: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
    Error: JTAG tap: lc_ctrl.tap  expected 1 of 1: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0)
    Error: Trying to use configured scan chain anyway...
    Warn : Bypassing JTAG setup events due to errors
    Error: Debug Module did not become active. dmcontrol=0x0
    Warn : target lc_ctrl.tap.0 examination failed
    Info : starting gdb server for lc_ctrl.tap.0 on 3333
    Info : Listening on port 3333 for gdb connections

With this commit, the warning has disappeared and the ID matches the
newly-hardcoded TAP ID.

    Info : Hardware thread awareness created
    Info : clock speed 200 kHz
    Info : JTAG tap: lc_ctrl.tap tap/device found: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
    Error: Debug Module did not become active. dmcontrol=0x0
    Warn : target lc_ctrl.tap.0 examination failed
    Info : starting gdb server for lc_ctrl.tap.0 on 3333
    Info : Listening on port 3333 for gdb connections

Fixes #17634

Signed-off-by: Dan McArdle <dmcardle@opentitan.org>