[gpio] Assert Known for outputs
Known assertions are added to make sure the outputs of GPIO have known
value.

Exception: other than interrupts, output port can be unknown if output
enable is de-asserted.

This is related to #405