[otbn] Add missing extern function declarations
GCC in CI doesn't complain, but GCC11 locally does.

```
../src/lowrisc_ip_otbn_top_sim_0.1/otbn_top_sim.cc: In function ‘int main(int, char**)’:
../src/lowrisc_ip_otbn_top_sim_0.1/otbn_top_sim.cc:121:21: error: ‘otbn_err_get’ was not declared in this scope
  121 |   svBit model_err = otbn_err_get();
      |                     ^~~~~~~~~~~~
../src/lowrisc_ip_otbn_top_sim_0.1/otbn_top_sim.cc:186:23: error: ‘otbn_core_get_stop_pc’ was not declared in this scope
  186 |     int act_stop_pc = otbn_core_get_stop_pc();
      |                       ^~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Philipp Wagner <phw@lowrisc.org>